//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace R.DAL.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class agency
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public agency()
        {
            this.travels = new HashSet<travel>();
        }
    
        public int id { get; set; }
        public string agency_name { get; set; }
        public Nullable<int> id_ville { get; set; }
        public string adresse { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public byte[] logo { get; set; }
        public string username { get; set; }
        public string pass { get; set; }
    
        public virtual ville ville { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<travel> travels { get; set; }
    }
}
